### ISSUE TITLE
xit formatting is unreadable with a Nord color scheme 

### ISSUE THREAD

**Issue by skatkov** [jotaen/xit-sublime#10]
Great idea with xit, really love idea of saving everything in a plain text file!

I've immediately installed a plugin for sublime and tried this out. Unfortunately, I got a follow result:

![personal-xit-with-dark-theme](https://user-images.githubusercontent.com/544377/166122018-87c6a67c-ca54-4283-8829-0bb61f96c2d5.png)

Formatting style/coloring doesn't play with my color_scheme.

Here is my current **preferences.sublime-settings** :
```
{
...
"color_scheme": "Packages/Nord/Nord.sublime-color-scheme",
..
}
```

## Workaround
Changing color-scheme helps

Monokai theme already looks workable
![xit-monokai-theme](https://user-images.githubusercontent.com/544377/166122166-5623e931-c1d6-491c-b492-cc136349af08.png)

But I've noticed, that Mariana theme is closer to my original Nord theme. So I'll stick with this one for a time being.
![xt-mariana-theme](https://user-images.githubusercontent.com/544377/166122167-c0e24954-a45b-4895-b9a0-6b97ed0d2bbc.png)

## Expected result
I am uncertain whether fix should be implemented in **xit-sublime** plugin or this is an issue related to **nord scheme** itself. 

But since this plugin is newer, I've decided to start off with writing this issue. I'd love to make this plugin play well with my original scheme. 

Any advice how I could do that? What could be the problem?

## Setup details:
Sublime version 4126
OS: Manjaro OS (Arch based)

**Comment by jotaen** [comment]
Thanks for the detailed report! The colours are set up to look nice with most available colour schemes, but in some cases it doesn’t work out, unfortunately. This is mainly an issue with the colour scheme itself. In case the colour scheme can’t be fixed directly, there are luckily some options to help yourself: (see the [Readme](https://github.com/jotaen/xit-sublime#syntax-highlighting--colour-overrides) for more info)

- Specify colour overrides for your chosen scheme that are specific to [x]it!, by means of the dedicated scopes such as `markup.other.checkbox.ongoing.xit`.
- Configure Sublime to always switch to a specific scheme (such as Monokai) when using [x]it! syntax.

Backstory: This package uses the [default colour scopes](https://www.sublimetext.com/docs/scope_naming.html) for assigning colours to [x]it! syntax. For example, the `[@]` token should be coloured in the same way as a numeric constant in other languages/syntaxes is. So if the `[@]` wouldn’t look nice, then other languages/syntaxes are prone to the same problem. The idea in Sublime Text generally is that every colour scheme is supposed to provide sensible colours for the default scopes, since they are widely used by syntaxes. For packages in Package Control, it’s also discouraged to ship colour overrides or fixes for specific schemes, since this can potentially create annoyances for users.
