### ISSUE TITLE
Macros in `v1.0.0` don’t work

### ISSUE THREAD

**Issue by ryanolsonx** [jotaen/xit-sublime#3]
This is reproducible installing via Git AND package control (it's LIVE 🎉  btw).

When I enter a .xit file, if I try to start a checkbox (such as typing "[" to a new xit file), it gives the error "Unable to open res://Packages/xit/macros/Insert Open Checkbox.sublime-macro".

**Comment by jotaen** [comment]
The package went through super quickly (usually it takes at least a couple of days for new Sublime Packages), but I screwed up version 1.0.0

This issue is fixed in https://github.com/jotaen/xit-sublime/releases/tag/1.1.0, but Package Control hasn’t picked that up yet. (Apparently it takes some time for that to happen…)

**Comment by jotaen** [comment]
(Leaving this issue open until the fix is published, in case anyone else stumbled across this.)

**Comment by ryanolsonx** [comment]
Good to know. Thanks!

I've been waiting for package control to pick up my changes to my [Zenburn color scheme](https://github.com/ryanolsonx/sublimetext-zenburn-theme). It becomes a waiting game...

**Comment by jotaen** [comment]
[`v1.1.1` live now](https://packagecontrol.io/packages/xit%21).

Cool colour theme, by the way, I like it!
